name: ObjectForm

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  spm:
    name: Test with SPM
    runs-on: macos-latest    
    env: 
      DEVELOPER_DIR: /Applications/Xcode_16.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: xcodebuild build -destination "name=iPhone 16" -scheme "ObjectForm"
